ibexa:
    system:
        default:
            image_host: /
            image_variations:
                i30:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [30] }
                        - { name: strip }
                i160:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [160] }
                        - { name: strip }
                i320:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [320] }
                        - { name: strip }
                i480:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [480] }
                        - { name: strip }
                i770:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [770] }
                        - { name: strip }
                i1320:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1320] }
                        - { name: strip }
                i1920:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1920] }
                        - { name: strip }

liip_imagine:
    default_filter_set_settings:
        format: webp
    filter_sets:
        small:
            quality: 85
            jpeg_quality: 85
            # format can also be defined per filter
            #format: webp
        medium:
            quality: 85
            jpeg_quality: 85
        large:
            quality: 85
            jpeg_quality: 85
        i30:
            quality: 20
            jpeg_quality: 20
        i160:
            quality: 85
            jpeg_quality: 85
        i320:
            quality: 85
            jpeg_quality: 85
        i480:
            quality: 85
            jpeg_quality: 85
        i770:
            quality: 85
            jpeg_quality: 85
        i1320:
            quality: 75
            jpeg_quality: 75
        i1920:
            quality: 75
            jpeg_quality: 75
